### ISSUE TITLE
Can't generate devise model with nobrainer ORM from inside of rails engine.

### ISSUE THREAD

**Issue by buyaka** [NoBrainerORM/devise-nobrainer#1]
can't generate devise model with nobrainer ORM from inside of rails engine. Devise model was generated with activerecord ORM.

**Comment by nviennot** [comment]
Can you be more specific?

**Comment by buyaka** [comment]
#### first I created new engine  for rails app

rails plugin new resolver --mountable 

#### and next

#### Added below lines into my resolver engine Gemfile

gem 'nobrainer'
gem 'devise-nobrainer'

#### and devise install

rails g devise:install

#### next is modified devise.rb initializer

#### in config/initializers/devise.rb

'devise/orm/active-record' -> 'devise/orm/nobrainer'

#### at the end

rails g devise Member

then devise model (member.rb) is

``` ruby
module Resolver
  class Member < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
  end
end
```

**Comment by nviennot** [comment]
I have no expertise in Rails engines. However I tried what you did, and it seems that there is nothing in `config/initializers/*` that gets loaded. Even if I put garbage in the initializer file, nothing happens.
The problem is not devise-nobrainer, but more in the way a rails engine gets initialized.
